tasks:
  default:
    build:
      trigger:
        - test
      pre_cmd:
        - echo "Pre command"
        - ls -l
        - ps -ef
        - ls -l node_modules || echo "not found"
        - env
        - echo $DOPS_SECRET || echo "DOPS_SECRET not found"
      bazel_flags:
        - "--keep_going"
      bazel_cmd:
        - "//..."
      post_cmd:
        - echo "Post command"
    test:
      bazel_flags:
        - "--keep_going"
      bazel_cmd:
        - "//..."
  windows10:
    build:
      disable: true
      trigger:
        - test
      bazel_flags:
        - "--keep_going"
      pre_cmd:
        - dir
      bazel_cmd:
        - "//..."
      post_cmd:
        - dir
    test:
      disable: true
      bazel_flags:
        - "--keep_going"
      bazel_cmd:
        - "//..."
