tasks:
  default:
    shell_command:
      disable: true
      pre_cmd:
      cmd:
        - bazel build //...
        - bazel test //...
      post_cmd:
    build:
      disable: false
      pre_cmd:
        - ps -ef
        - ls -l
      bazel_flags:
        - "--keep_going"
      bazel_cmd:
        - "//..."
      post_cmd:
        - ps -ef | grep bazel
    test:
      disable: false
      bazel_flags:
        - "--keep_going"
      bazel_cmd:
        - "//..."
    test_sharding:
      disable: true
      parallel: 4
  windows10:
    build:
      bazel_flags:
        - "--keep_going"
      pre_cmd:
        - dir
      bazel_cmd:
        - "//..."
      post_cmd:
        - dir
